<a href="https://colab.research.google.com/github/Harshalbaid12/E-commerce-Interface/blob/master/Stress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving Dataset.xlsx to Dataset.xlsx


In [2]:
stress = pd.read_excel("Dataset.xlsx")
stress

Nervousness Unable to control     Worry Trouble in Relaxation  \
0          Severe          Moderate      Mild                    No   
1              No                No      Mild                  Mild   
2          Severe            Severe      Mild                Severe   
3              No            Severe    Severe                  Mild   
4            Mild                No        No                    No   
...           ...               ...       ...                   ...   
16379        Mild            Severe      Mild                    No   
16380        Mild                No        No                    No   
16381          No          Moderate  Moderate                  Mild   
16382      Severe              Mild    Severe                  Mild   
16383    Moderate          Moderate  Moderate              Moderate   

      Restlessness Irritability      Fear    Stress  
0             Mild         Mild        No      Mild  
1               No         Mild  Moderate      Mild  
2           Severe         Mild    Severe    Severe  
3           Severe           No    Severe  Moderate  
4               No           No      Mild        No  
...            ...          ...       ...       ...  
16379     Moderate           No      Mild      Mild  
16380       Severe           No        No        No  
16381       Severe           No  Moderate      Mild  
16382           No         Mild    Severe  Moderate  
16383       Severe     Moderate  Moderate  Moderate  

[16384 rows x 8 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
x = stress.iloc[:,:-1]
y = stress.Stress

x = x.apply(encoder.fit_transform)
x

Nervousness  Unable to control  Worry  Trouble in Relaxation  \
0                3                  1      0                      2   
1                2                  2      0                      0   
2                3                  3      0                      3   
3                2                  3      3                      0   
4                0                  2      2                      2   
...            ...                ...    ...                    ...   
16379            0                  3      0                      2   
16380            0                  2      2                      2   
16381            2                  1      1                      0   
16382            3                  0      3                      0   
16383            1                  1      1                      1   

       Restlessness  Irritability  Fear  
0                 0             0     2  
1                 2             0     1  
2                 3             0     3  
3                 3             2     3  
4                 2             2     0  
...             ...           ...   ...  
16379             1             2     0  
16380             3             2     2  
16381             3             2     1  
16382             2             0     3  
16383             3             1     1  

[16384 rows x 7 columns]

In [17]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,ConfusionMatrixDisplay,classification_report
from sklearn.neighbors import KNeighborsClassifier

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/4,random_state=1)
regressor = DecisionTreeClassifier()
decision_tree = regressor.fit(x_train,y_train)
y_pred_dt = decision_tree.predict(x_test)
score = accuracy_score(y_test,y_pred_dt) 
print(score)




0.739501953125


KNN Classifier


In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10,metric='manhattan')
classifier.fit(x_train, y_train)
y_pred_knn = classifier.predict(x_test)
score = accuracy_score(y_test,y_pred_knn)
print(score)

0.747314453125


In [18]:
print(confusion_matrix(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_knn))


[[1488  438   37    0]
 [ 345 1393    0  105]
 [  55    0   42    0]
 [   0   87    0  106]]
[[1654  309    0    0]
 [ 454 1387    0    2]
 [  91    0    6    0]
 [   1  178    0   14]]


In [19]:
print(classification_report(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

        Mild       0.79      0.76      0.77      1963
    Moderate       0.73      0.76      0.74      1843
          No       0.53      0.43      0.48        97
      Severe       0.50      0.55      0.52       193

    accuracy                           0.74      4096
   macro avg       0.64      0.62      0.63      4096
weighted avg       0.74      0.74      0.74      4096

              precision    recall  f1-score   support

        Mild       0.75      0.84      0.79      1963
    Moderate       0.74      0.75      0.75      1843
          No       1.00      0.06      0.12        97
      Severe       0.88      0.07      0.13       193

    accuracy                           0.75      4096
   macro avg       0.84      0.43      0.45      4096
weighted avg       0.76      0.75      0.73      4096

